# Generated by Django 6.1 on 2026-09-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'ordering': ['-created_at'], 'permissions': [('review_approvalrequest', 'Can approve or reject approval request')]},
        ),
    ]
