# Generated by Django 6.1 on 2026-09-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_approvalrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='review_comment',
            field=models.TextField(blank=True),
        ),
    ]
