# Generated by Django 6.1 on 2026-09-08 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_approvalrequest_review_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(('checker__isnull', True), models.Q(('maker', models.F('checker')), _negated=True), _connector='OR'), name='approval_checker_differs_from_maker'),
        ),
    ]
