# Generated by Django 6.1 on 2026-09-08 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_approvalrequest_approval_checker_differs_from_maker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('checker__isnull', True), ('reviewed_at__isnull', True), ('status', 'PENDING')), models.Q(('checker__isnull', False), ('reviewed_at__isnull', False), ('status__in', ['APPROVED', 'REJECTED'])), _connector='OR'), name='approval_review_state_consistent'),
        ),
    ]
