# Generated by Django 6.1 on 2026-08-23 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trade_orders', '0003_shipmentpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('currency_purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_logs', to='trade_orders.currencypurchase')),
            ],
            options={
                'db_table': 'notification_logs',
                'indexes': [models.Index(fields=['currency_purchase', 'notification_type'], name='idx_notification_purchase_type')],
                'constraints': [models.UniqueConstraint(fields=('currency_purchase', 'notification_type'), name='unique_notification_per_purchase')],
            },
        ),
    ]
