# Generated by Django 6.1 on 2026-09-18 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('notifications', '0001_initial'),
        ('trade_orders', '0013_alter_currencypurchase_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('IN_APP', 'In app'), ('SMS', 'SMS')], max_length=20)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=60)),
                ('provider_message_id', models.CharField(blank=True, max_length=160)),
                ('error_message', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification_deliveries',
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('BANK_USER', 'Bank user'), ('COMPANY_CONTACT', 'Company contact')], db_index=True, max_length=30)),
                ('display_name', models.CharField(max_length=160)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_recipients',
            },
        ),
        migrations.RemoveConstraint(
            model_name='notificationlog',
            name='unique_notification_per_purchase',
        ),
        migrations.RenameField(
            model_name='notificationlog',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='deadline_kind',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(max_length=80),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['deadline_date', 'notification_type'], name='idx_notification_deadline_type'),
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(fields=('currency_purchase', 'notification_type', 'deadline_kind', 'deadline_date'), name='unique_notification_event_per_deadline'),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='notifications.notificationlog'),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_recipients', to='companies.company'),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_recipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='notifications.notificationrecipient'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['recipient_type', 'is_active'], name='notif_recip_ty_act_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['company', 'is_active'], name='idx_notif_recipient_company'),
        ),
        migrations.AddConstraint(
            model_name='notificationrecipient',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('company__isnull', True), ('recipient_type', 'BANK_USER')), models.Q(('company__isnull', False), ('recipient_type', 'COMPANY_CONTACT'), ('user__isnull', True)), _connector='OR'), name='notification_recipient_scope_valid'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['status', 'channel'], name='notif_deliv_st_ch_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('notification', 'recipient', 'channel'), name='unique_notification_delivery_recipient_channel'),
        ),
    ]
