# Generated by Django 6.1 on 2026-09-14 14:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0005_approvalrequest_approval_review_state_consistent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('VOID', 'Void'), ('DELETE', 'Delete'), ('REQUEST_SUBMITTED', 'Request submitted'), ('REQUEST_APPROVED', 'Request approved'), ('REQUEST_REJECTED', 'Request rejected')], db_index=True, max_length=40)),
                ('target_type', models.CharField(db_index=True, max_length=120)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='workflows.approvalrequest')),
            ],
            options={
                'db_table': 'audit_events',
                'ordering': ['-created_at'],
                'permissions': [('view_sensitive_audit', 'Can view sensitive audit trail')],
                'indexes': [models.Index(fields=['target_type', 'target_id', 'created_at'], name='idx_audit_target_created'), models.Index(fields=['actor', 'created_at'], name='idx_audit_actor_created')],
            },
        ),
    ]
