# Generated by Django 6.1 on 2026-08-22 12:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50)),
                ('registered_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_orders', to='companies.company')),
            ],
            options={
                'db_table': 'registration_orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='idx_order_company_active')],
                'constraints': [models.UniqueConstraint(fields=('company', 'order_number'), name='unique_order_number_per_company')],
            },
        ),
    ]
