# Generated by Django 6.1 on 2026-08-22 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('purchase_date', models.DateField()),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_purchases', to='trade_orders.registrationorder')),
            ],
            options={
                'db_table': 'currency_purchases',
                'ordering': ['purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInstrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_instrument', to='trade_orders.registrationorder')),
            ],
            options={
                'db_table': 'payment_instruments',
            },
        ),
    ]
