# Generated by Django 6.1 on 2026-08-22 12:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_orders', '0002_currencypurchase_paymentinstrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_parts', to='trade_orders.currencypurchase')),
            ],
            options={
                'db_table': 'shipment_parts',
                'ordering': ['-received_date', '-created_at'],
                'indexes': [models.Index(fields=['currency_purchase', 'received_date'], name='idx_shipment_purchase_received')],
            },
        ),
    ]
