# Generated by Django 6.1 on 2026-09-08 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_orders', '0003_shipmentpart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypurchase',
            name='is_void',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='currencypurchase',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='currencypurchase',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currencypurchase',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_currency_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='currencypurchase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_void', False), ('void_reason', ''), ('voided_at__isnull', True), ('voided_by__isnull', True)), models.Q(('is_void', True), ('voided_at__isnull', False), ('voided_by__isnull', False)), _connector='OR'), name='currency_purchase_void_state_consistent'),
        ),
    ]
