# Generated by Django 6.1 on 2026-09-08 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_orders', '0004_currencypurchase_is_void_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencypurchase',
            options={'ordering': ['purchase_date'], 'permissions': [('void_currencypurchase', 'Can submit currency purchase void request')]},
        ),
    ]
