# Generated by Django 6.1 on 2026-09-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_orders', '0005_alter_currencypurchase_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='currencypurchase',
            name='currency_purchase_void_state_consistent',
        ),
    ]
