# Generated by Django 6.1 on 2026-09-08 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_orders', '0006_remove_currencypurchase_currency_purchase_void_state_consistent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='currencypurchase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_void', False), ('void_reason', ''), ('voided_at__isnull', True), ('voided_by__isnull', True)), models.Q(('is_void', True), ('voided_at__isnull', False), ('voided_by__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='currency_purchase_void_state_consistent'),
        ),
    ]
