# Generated by Django 6.1 on 2026-09-12 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_orders', '0007_currencypurchase_currency_purchase_void_state_consistent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentpart',
            options={'ordering': ['-received_date', '-created_at'], 'permissions': [('void_shipmentpart', 'Can submit shipment part void request')]},
        ),
        migrations.AddField(
            model_name='shipmentpart',
            name='is_void',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='shipmentpart',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipmentpart',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentpart',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_shipment_parts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='shipmentpart',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_void', False), ('void_reason', ''), ('voided_at__isnull', True), ('voided_by__isnull', True)), models.Q(('is_void', True), ('voided_at__isnull', False), ('voided_by__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='shipment_part_void_state_consistent'),
        ),
    ]
