# Generated by Django 6.1 on 2026-09-17 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_orders', '0009_currencypurchase_deadline_extension_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypurchase',
            name='obligation_settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currencypurchase',
            name='obligation_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('DOCUMENTS_COMPLETE', 'Documents complete'), ('CLEARANCE_PENDING', 'Clearance pending'), ('PARTIALLY_CLEARED', 'Partially cleared'), ('CLEARED', 'Cleared'), ('SETTLED', 'FX obligation settled'), ('OVERDUE', 'Overdue')], db_index=True, default='OPEN', max_length=30),
        ),
        migrations.AddField(
            model_name='paymentinstrument',
            name='issue_date',
            field=models.DateField(blank=True, help_text='Issue/opening/registration date of the payment instrument.', null=True),
        ),
        migrations.AddField(
            model_name='paymentinstrument',
            name='operation_type',
            field=models.CharField(choices=[('REMITTANCE', 'FX Remittance'), ('DOCUMENTARY_COLLECTION', 'Documentary Collection'), ('LETTER_OF_CREDIT', 'Letter of Credit'), ('OTHER', 'Other')], db_index=True, default='REMITTANCE', max_length=40),
        ),
        migrations.CreateModel(
            name='RegulatoryRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('operation_type', models.CharField(choices=[('REMITTANCE', 'FX Remittance'), ('DOCUMENTARY_COLLECTION', 'Documentary Collection'), ('LETTER_OF_CREDIT', 'Letter of Credit'), ('OTHER', 'Other')], db_index=True, max_length=40)),
                ('activity_type', models.CharField(blank=True, choices=[('COMMERCIAL', 'Commercial'), ('PRODUCTION', 'Production')], db_index=True, max_length=20, null=True)),
                ('deadline_kind', models.CharField(choices=[('IMPORT_CLEARANCE', 'Import/clearance deadline'), ('SHIPPING_DOCUMENTS', 'Shipping-document deadline'), ('FX_DIFFERENCE', 'FX-difference deadline')], default='IMPORT_CLEARANCE', max_length=40)),
                ('deadline_basis', models.CharField(choices=[('PURCHASE_DATE', 'Currency funding/purchase date'), ('REMITTANCE_DATE', 'Remittance date'), ('INSTRUMENT_DATE', 'Payment instrument date')], max_length=30)),
                ('deadline_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deadline_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('internal_reference', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'regulatory_rules',
                'ordering': ['priority', '-effective_from', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('deadline_months__isnull', False), ('deadline_days__isnull', True)), models.Q(('deadline_months__isnull', True), ('deadline_days__isnull', False)), _connector='OR'), name='regulatory_rule_exactly_one_duration')],
            },
        ),
        migrations.AddField(
            model_name='currencypurchase',
            name='applied_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency_purchases', to='trade_orders.regulatoryrule'),
        ),
        migrations.CreateModel(
            name='CustomsClearance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('declaration_number', models.CharField(max_length=100)),
                ('clearance_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('status', models.CharField(choices=[('DECLARED', 'Declared'), ('PARTIAL', 'Partially cleared'), ('FINAL', 'Final clearance'), ('REJECTED', 'Rejected/invalid')], db_index=True, default='DECLARED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customs_clearances', to='trade_orders.currencypurchase')),
            ],
            options={
                'db_table': 'customs_clearances',
                'ordering': ['-clearance_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('currency_purchase', 'declaration_number'), name='unique_clearance_per_purchase_declaration'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='customs_clearance_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='DeadlineExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_deadline', models.DateField()),
                ('new_deadline', models.DateField()),
                ('reason', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_deadline_extensions', to=settings.AUTH_USER_MODEL)),
                ('currency_purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deadline_extensions', to='trade_orders.currencypurchase')),
            ],
            options={
                'db_table': 'deadline_extensions',
                'ordering': ['created_at'],
                'permissions': [('extend_currencypurchase_deadline', 'Can extend currency purchase deadline')],
                'constraints': [models.CheckConstraint(condition=models.Q(('new_deadline__gt', models.F('previous_deadline'))), name='deadline_extension_moves_forward')],
            },
        ),
    ]
