# Generated by Django 6.1 on 2026-09-17 05:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_orders', '0010_currencypurchase_obligation_settled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypurchase',
            name='funding_source_code',
            field=models.CharField(blank=True, db_index=True, help_text='Internal code for the FX funding/source category used by the verified regulatory matrix.', max_length=80),
        ),
        migrations.AddField(
            model_name='registrationorder',
            name='goods_category_code',
            field=models.CharField(blank=True, db_index=True, help_text='Internal regulatory goods-category code. Keep this code aligned with the verified regulatory matrix; blank means unclassified.', max_length=80),
        ),
        migrations.AddField(
            model_name='regulatoryrule',
            name='funding_source_code',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='regulatoryrule',
            name='goods_category_code',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='currencypurchase',
            name='remittance_date',
            field=models.DateField(blank=True, help_text='Actual remittance issue date. Required only when a selected regulatory rule uses REMITTANCE_DATE as its basis.', null=True),
        ),
        migrations.CreateModel(
            name='RegulatoryDeadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deadline_kind', models.CharField(choices=[('IMPORT_CLEARANCE', 'Import/clearance deadline'), ('SHIPPING_DOCUMENTS', 'Shipping-document deadline'), ('FX_DIFFERENCE', 'FX-difference deadline')], db_index=True, max_length=40)),
                ('basis_date', models.DateField()),
                ('original_deadline', models.DateField()),
                ('effective_deadline', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_deadlines', to='trade_orders.regulatoryrule')),
                ('currency_purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_deadlines', to='trade_orders.currencypurchase')),
            ],
            options={
                'db_table': 'regulatory_deadlines',
                'ordering': ['effective_deadline', 'deadline_kind'],
            },
        ),
        migrations.AddField(
            model_name='deadlineextension',
            name='regulatory_deadline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extensions', to='trade_orders.regulatorydeadline'),
        ),
        migrations.AddConstraint(
            model_name='regulatorydeadline',
            constraint=models.UniqueConstraint(fields=('currency_purchase', 'deadline_kind'), name='unique_deadline_kind_per_purchase'),
        ),
        migrations.AddConstraint(
            model_name='regulatorydeadline',
            constraint=models.CheckConstraint(condition=models.Q(('effective_deadline__gte', models.F('original_deadline'))), name='reg_deadline_effective_gte_original'),
        ),
    ]
