# Generated by Django 6.1 on 2026-09-18 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_orders', '0011_currencypurchase_funding_source_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypurchase',
            name='obligation_settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settled_currency_purchase_obligations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencypurchase',
            name='obligation_settlement_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='currencypurchase',
            name='obligation_settlement_reference',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
