# Generated by Django 6.1 on 2026-09-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_orders', '0012_currencypurchase_obligation_settled_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencypurchase',
            options={'ordering': ['purchase_date'], 'permissions': [('void_currencypurchase', 'Can submit currency purchase void request'), ('settle_currencypurchase_obligation', 'Can settle or reopen currency purchase FX obligation')]},
        ),
    ]
