# Generated by Django 6.1 on 2026-08-22 12:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trade_orders', '0003_shipmentpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fob_amount', models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('freight_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=4, editable=False, max_digits=20)),
                ('submission_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_part', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='trade_orders.shipmentpart')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-submission_date'],
            },
        ),
    ]
